### ISSUE TITLE
Can't export: 'NoneType' does not support the buffer interface

### ISSUE THREAD

**Issue by phils** [echoma/zkui#1]
Tried to export from a zookeeper cluster to local disk on Windows 7.

Error:
Export failed, err=exception, 'NoneType' does not support the buffer interface

Not sure what other info might be helpful.  It does create the export dir and puts a couple of empty files in there.

**Comment by echoma** [comment]
Hmm, a little diffcult to indicate the problem
- Are you using the latest pre-built executable(zkui_win_20150502.zip)?
- Could you please tell me the parameters you input in the "Export Dialog", such as "Path","Export To Local Directory","Without ACL"?
- Are the node data in binary format or just plain text?
- What's the size of your node count? hundreds or thousands?

**Comment by echoma** [comment]
I uploaded a new package here: https://github.com/echoma/zkui/wiki/Download
Could you please download and check whether the bug is fixed?

**Comment by phils** [comment]
Apologies, did not see your response (though I didn't need the tool anymore).  Not seeing this on the latest version.  I am however running into a new issue with colon symbol in dir name not working on windows :)
