### ISSUE TITLE
Need a scroll bar in the left panel

### ISSUE THREAD

**Issue by sunnykaka** [echoma/zkui#4]
Nice project.

I have hundreds ZNode in my zookeeper.

But only a few of them can show in the ui.

A scroll bar would be of a great help to me.

**Comment by sunnykaka** [comment]
Here is a screenshot.
![qq 20160126140644](https://cloud.githubusercontent.com/assets/1176838/12573633/27f6ed62-c436-11e5-968d-c51c305af29d.png)

**Comment by echoma** [comment]
I will fix this as soon as possible. And I also see the long node names are shown incorrectly, I will find a way to solve this.

**Comment by sunnykaka** [comment]
Looking forward to this patch :)

**Comment by echoma** [comment]
Would you please download the new package from [here](https://github.com/echoma/zkui/wiki/prebuild/win/zkui_win_20160128.zip) and check whether it performs correctly for you?

**Comment by sunnykaka** [comment]
It works.Thanks a lot.
