### ISSUE TITLE
Can't click on Znode path gets no response.

### ISSUE THREAD

**Issue by sunnykaka** [echoma/zkui#5]
Click on the ZNode in the left panel gets no response.

I wonder if the ZNode path is too long.

![qq 20160129163346](https://cloud.githubusercontent.com/assets/1176838/12671308/9c67b422-c6a9-11e5-9b4e-e064134eec16.png)

Right click on the ZNode and click "copy link" got this text:

```
javascript:zkuiRefreshPath(%22/dubbo/com.neo.xnol.my.account.service.AccountService/providers/dubbo%3A%2F%2F172.20.20.202%3A6006%2Fcom.neo.xnol.my.account.service.AccountService%3Faccepts%3D1024%26accesslog%3Dtrue%26anyhost%3Dtrue%26application%3DMyAccount_RPC_Server%26charset%3DUTF-8%26default.cluster%3Dfailfast%26default.delay%3D-1%26default.loadbalance%3Dleastactive%26default.timeout%3D30000%26default.version%3D2.0.2%26delay%3D-1%26dubbo%3D1.2.1-SNAPSHOT%26interface%3Dcom.neo.xnol.my.account.service.AccountService%26methods%3DgetInvestStatistics%2CqueryOfLateIncome%2CfindRecommendProduct%2CgetAccountData%26pid%3D20485%26revision%3D2.39.0-SNAPSHOT%26side%3Dprovider%26timestamp%3D1454256853405%22)
```

**Comment by echoma** [comment]
emm, it seems that the %XX charactors are incorrectly escaped. I will look into this right now.

**Comment by echoma** [comment]
Would you please download the new package from [here](https://github.com/echoma/zkui/wiki/prebuild/win/zkui_win_20160129.zip) and check whether it performs correctly for you?

**Comment by sunnykaka** [comment]
The bug is gone, thanks.
